version: "3.9"

services:
  api:
    image: gelada-api
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      MONGO_URI: ${MONGO_URI}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      COGNITO_USER_POOL_ID: ${COGNITO_USER_POOL_ID}
      COGNITO_CLIENT_ID: ${COGNITO_CLIENT_ID}
      NODE_ENV: production
      PORT: 3000
    ports:
      - "80:3000"
